DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'teste') THEN
    CREATE ROLE teste LOGIN PASSWORD 'teste';
  END IF;
END $$;

GRANT USAGE ON SCHEMA public TO teste;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO teste;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO teste;



