version: "3.9"

services:
  api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    networks:
      - default
      - pg_shared

networks:
  pg_shared:
    external: true


